# Generated by Django 5.2.16 on 2026-08-05 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kredit_program', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kreditprogram',
            name='jenis_soa',
            field=models.CharField(choices=[('KLAIM', 'Klaim'), ('PREMI', 'Premi')], default='KLAIM', max_length=10),
        ),
    ]
