# Generated by Django 5.2.16 on 2026-08-05 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('main_file_name', models.CharField(max_length=255)),
                ('reference_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('total_rows', models.IntegerField(default=0)),
                ('unmapped_cob_count', models.IntegerField(default=0)),
            ],
        ),
    ]
