# Generated by Django 5.2.16 on 2026-07-28 07:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asum',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('main_filename', models.CharField(max_length=255)),
                ('reference_filename', models.CharField(max_length=255)),
                ('total_rows_processed', models.IntegerField(default=0)),
                ('jenis_soa', models.CharField(choices=[('KLAIM', 'Klaim'), ('PREMI', 'Premi')], default='KLAIM', max_length=10)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
